# Generated by Django 4.1 on 2022-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hr_hradmin_data_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrName', models.TextField(max_length=100, null='true')),
                ('company_name', models.TextField(max_length=100, null='true')),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('password', models.TextField(max_length=100, null='true')),
                ('confirm_password', models.TextField(max_length=100, null='true')),
            ],
            options={
                'db_table': 'hr_hradmin_db_table',
            },
        ),
    ]
