# Generated by Django 4.1 on 2022-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_hradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hradmin_data_table',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
