# Generated by Django 4.1 on 2022-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_hradmin', '0002_alter_hr_hradmin_data_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_hradmin_data_table',
            name='email',
            field=models.EmailField(max_length=100, unique='True'),
        ),
    ]
