# Generated by Django 4.1 on 2022-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_hradmin', '0003_alter_hr_hradmin_data_table_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_hradmin_data_table',
            name='company_name',
            field=models.TextField(max_length=100, null='true'),
            preserve_default='true',
        ),
    ]
