# Generated by Django 4.0.4 on 2022-08-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hr_applicant_data_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantName', models.TextField(max_length=100, null='true')),
                ('email', models.EmailField(max_length=100, unique='True')),
                ('cv', models.FileField(null='true')),
                ('ccat_score', models.TextField(max_length=100, null='true')),
                ('testgorila_score', models.TextField(max_length=100, null='true')),
            ],
            options={
                'db_table': 'hr_applicant_data_table',
            },
        ),
    ]
