# Generated by Django 4.1 on 2022-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_data_table',
            name='user',
        ),
        migrations.AddField(
            model_name='applicant_data_table',
            name='applicantName',
            field=models.CharField(max_length=100, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='applicant_data_table',
            name='email',
            field=models.EmailField(max_length=100, null='true'),
            preserve_default='true',
        ),
    ]
