# Generated by Django 4.1 on 2022-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_candidate', '0002_remove_applicant_data_table_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_data_table',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
