# Generated by Django 4.1 on 2022-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_candidate', '0003_alter_hr_applicant_data_table_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_applicant_data_table',
            name='applicantName',
            field=models.CharField(max_length=100, null='true'),
        ),
    ]
