# Generated by Django 4.1 on 2022-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_candidate', '0004_alter_hr_applicant_data_table_applicantname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_applicant_data_table',
            name='password',
            field=models.CharField(max_length=100, null='true'),
            preserve_default='true',
        ),
    ]
