# Generated by Django 4.1 on 2022-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_candidate', '0005_hr_applicant_data_table_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_applicant_data_table',
            name='password',
            field=models.CharField(max_length=50, null='true'),
        ),
    ]
