# Generated by Django 4.1 on 2022-09-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAutomation_candidate', '0006_alter_hr_applicant_data_table_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_applicant_data_table',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
